modules:
  pxgeneric:
    walk:
      - bgpPeerRemoteAddr
      - cbgpPeer2AdminStatus
      - cbgpPeer2FsmEstablishedTime
      - cbgpPeer2State
      - cbgpPeerAcceptedPrefixes
      - cbgpPeerAddrFamilyAfi
      - cbgpPeerAddrFamilySafi
      - cbgpPeerAdvertisedPrefixes
      - cbgpPeerDeniedPrefixes
      - cbgpPeerSuppressedPrefixes
      - cbgpPeerWithdrawnPrefixes
      - ccmHistoryRunningLastChanged
      - ccmHistoryRunningLastSaved
      - cefcFRUPowerAdminStatus
      - cefcFRUPowerOperStatus
      - entPhysicalName
      - entPhysicalDescr
      - entSensorThresholdSeverity
      - entSensorThresholdValue
      - entSensorType
      - entSensorValue
      - ifInDiscards
      - ifInErrors
      - ifHCInOctets
      - ifHCInUcastPkts
      - ifInUnknownProtos
      - ifLastChange
      - ifOutDiscards
      - ifOutErrors
      - ifHCOutOctets
      - ifOutQLen
      - ifHCOutUcastPkts
      - rttMonJitterStatsPacketLossDS
      - rttMonJitterStatsPacketLossSD
      - rttMonJitterStatsPacketOutOfSequence
      - rttMonJitterStatsCompletions
      - rttMonJitterStatsStartTimeIndex
      - rttMonJitterStatsNumOfRTT
      - rttMonJitterStatsRTTSum
      - rttMonJitterStatsAvgJitter
      - rttMonLatestRttOperSense
      - rttMonLatestRttOperTime
      - rttMonEchoAdminCodecNumPackets
      - sysUpTime
      - sysDescr
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        lookup: ifDescr
      - source_indexes: [ifIndex]
        lookup: ifType
      - source_indexes: [ifIndex]
        lookup: ifMtu
      - source_indexes: [ifIndex]
        lookup: ifHighSpeed
      - source_indexes: [ifIndex]
        lookup: ifPhysAddress
      - source_indexes: [ifIndex]
        lookup: ifAdminStatus
      - source_indexes: [ifIndex]
        lookup: ifOperStatus
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [rttMonCtrlAdminIndex]
        lookup: rttMonCtrlAdminOwner
      - source_indexes: [rttMonCtrlAdminIndex]
        lookup: rttMonCtrlAdminTag
      - source_indexes: [entPhysicalIndex]
        lookup: entPhysicalName
      - source_indexes: [entPhysicalIndex]
        lookup: entPhysicalDescr
    overrides:
      rttMonJitterStatsStartTimeIndex:
        ignore: false
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true
      ifName:
        ignore: true
      ifType:
        type: EnumAsInfo
      ifMtu:
        ignore: true
      ifHighSpeed:
        ignore: true
      ifPhysAddress:
        type: PhysAddress48
      ifAdminStatus:
        ignore: true
      ifOperStatus:
        ignore: true
      rttMonCtrlAdminOwner:
        ignore: true
      rttMonCtrlAdminTag:
        ignore: true
      FeatureName:
        ignore: true
      entPhyscalName:
        ignore: true