kind: Secret
apiVersion: v1

metadata:
  name: arc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"

data:
  ca.crt: {{.Values.ca.certificate | b64enc}}
  ca.key: {{.Values.ca.privateKey | b64enc}}
{{- if .Values.ca.certRevocationList }}
  ca.crl: {{.Values.ca.certRevocationList | b64enc}}
{{- end }}